
CREATE TABLE expenses (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    concept VARCHAR(100) NOT NULL,
    ammount DECIMAL(10 , 2 ) NOT NULL,
    interest_rate DECIMAL(3 , 2 ) NOT NULL DEFAULT 0,
    date_start DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_end DATETIME DEFAULT NULL,
    date_created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE incomes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    concept VARCHAR(100) NOT NULL,
    ammount DECIMAL(10 , 2 ) NOT NULL,
    is_active TINYINT NOT NULL DEFAULT 1,
    is_regular TINYINT NOT NULL DEFAULT 1,
    date_created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);