CREATE TABLE movements (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ammount DECIMAL(10 , 2 ) NOT NULL,
    account_id INT UNSIGNED NOT NULL,
    date_created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);